apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: redis
        ports:
        - containerPort: 6379
          name: redis-server
        resources:
          limits:
            cpu: "2"
            memory: "900Mi"
          requests:
            cpu: "1"
            memory: "450Mi"
